<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="8" passed="5" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-03T16:28:49 IST" name="Suite" finished-at="2022-05-03T16:28:49 IST" duration-ms="121">
    <groups>
    </groups>
    <test started-at="2022-05-03T16:28:49 IST" name="Test" finished-at="2022-05-03T16:28:49 IST" duration-ms="121">
      <class name="prachijoshi.AppiumTest">
        <test-method signature="methodA()[pri:0, instance:prachijoshi.AppiumTest@74751b3]" started-at="2022-05-03T16:28:49 IST" name="methodA" finished-at="2022-05-03T16:28:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodA -->
        <test-method signature="methodB()[pri:0, instance:prachijoshi.AppiumTest@74751b3]" started-at="2022-05-03T16:28:49 IST" name="methodB" finished-at="2022-05-03T16:28:49 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodB -->
      </class> <!-- prachijoshi.AppiumTest -->
      <class name="prachijoshi.RestAPITest">
        <test-method signature="methodC()[pri:0, instance:prachijoshi.RestAPITest@2b91004a]" started-at="2022-05-03T16:28:49 IST" name="methodC" finished-at="2022-05-03T16:28:49 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodC -->
        <test-method signature="methodD()[pri:0, instance:prachijoshi.RestAPITest@2b91004a]" started-at="2022-05-03T16:28:49 IST" name="methodD" finished-at="2022-05-03T16:28:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodD -->
      </class> <!-- prachijoshi.RestAPITest -->
      <class name="prachijoshi.SeleniumTest">
        <test-method signature="parent()[pri:0, instance:prachijoshi.SeleniumTest@21e360a]" started-at="2022-05-03T16:28:49 IST" name="parent" finished-at="2022-05-03T16:28:49 IST" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at prachijoshi.SeleniumTest.parent(SeleniumTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parent -->
        <test-method signature="methodF()[pri:0, instance:prachijoshi.SeleniumTest@21e360a]" started-at="2022-05-03T16:28:49 IST" name="methodF" finished-at="2022-05-03T16:28:49 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodF -->
        <test-method signature="child()[pri:0, instance:prachijoshi.SeleniumTest@21e360a]" started-at="2022-05-03T16:28:49 IST" name="child" finished-at="2022-05-03T16:28:49 IST" depends-on-methods="prachijoshi.SeleniumTest.parent" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumTest.child()[pri:0, instance:prachijoshi.SeleniumTest@21e360a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumTest.child()[pri:0, instance:prachijoshi.SeleniumTest@21e360a] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- child -->
      </class> <!-- prachijoshi.SeleniumTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
